name: Demo GitHub Action

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2001933@ds.study.iitm.ac.in
        run: echo "Hello, world!"
